name: Deploy

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: run pm2 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd $HOME/${{ github.event.repository.name }}/src
          git pull
          pm2 startOrRestart process.json --silent
